spring:
  application:
    name: practice

  test-a:
    datasource:
      hikari:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3306/qrdb
        username: user1
        password: user1
  test-b:
    datasource:
      hikari:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3306/test
        username: root
        password: maria

logging:
  level:
    web: info
    root: info
    com.jdh.dsTest: info
